---
title: "Emotional Hangover"
author: "Arun Koundinya Parasa"
date: "2019-07-15"
categories: [story, psychology]
---

What is Hangover?

We all know about Hangover to put in simple and my way "it is just hanging around unconsciously".

What is Emotional Hangover?

There are many definitions and my way to put is " Hanging unconsciously with a dense of emotions ". 

Why and how can there be an Emotional Hangover?
Emotional Hangover as I look at it; starts with normal symptoms such as lack of focus, anxiety, tension in the body, lack of motivation towards our health and few others. If we do not recognize these emotions they may aggravate and will effect our own life. 

To note, any bad incident that happens in our life can never be erased. It can only be forgotten.

Let us read this small story snippet to learn how Emotional Hangover kills us.

Story Snippet: { Story in First Person }

Hi Friends, my name is Rahul Sharma. Most of my friends and especially my close friends and well wishers used to say that "You are good at almost every thing, however if you can control your emotions; you reach to new heights". I used to think that "Lack of controlling our emotions is a cult and ignored it".

I realised that our true emotions comes out when our personal spaces overlap. Of course, when we are in relationship it is certain. Her name is *Supriya,* in initial days she enjoyed my love to full extent. Being more emotional ( as a lover we may not be able to control our emotions ) made her more gifted, excited and thrilled. Later after few months, my emotions led to break up. This made my emotional hangover further carried over to "alcohol over".

Later, after an year I have joined in my first company. In enthuse and being carried with the same emotional hang mentality, I was liked by all managers. The reason is being my stupendous productivity and involvement. However, later these own emotions again made myself complicated; leading my colleagues deserting my companionship; which finally lead to my resignation. This further made me loose my confidence, productivity, health, my goal and few others.

Later, after couple of years when my emotions regained to its normal state; and after thorough analysis within myself I felt that in both the episodes; i.e.; in my love as well as in my career my view is 100% right. It went wrong only in my expression. My analysis and thinking is perfect but when I'm expressing my views, my emotions over ruled unconsciously. That showcases a different picture leading for unnecessary conclusions on my personality. Certainly, when we are in high emotional state our unconscious brain hinds our conscious process of thinking making us difficult to express to what we want to express.

Also, being more emotional becomes a tool for others to fulfil their interests and goals.

I would like to stop the story at this juncture and leave the ending and conclusion to  your imagination.\
\
To Conclude, Self Disciple and Self Control towards our own emotions certainly will lead to a happy and prosperous life.\
\
To Note, even a small tweaking in our daily habits like daily jog/morning prayer will certainly lead to larger benefits of controlling our emotional hangover. " ***What do you think the reason for it? is it a Domino effect?***"