project:
  type: website

website:
  title: "Canvass And Analyze"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ArunKoundinya
      - icon: linkedin
        href: https://www.linkedin.com/in/arunkoundinya0710/
format:
  html:
    theme: slate
    css: styles.css



