---
title: "Responsibility"
author: "Arun Koundinya Parasa"
date: "2019-07-20"
categories: [reflection]
---

This fourteen letter word indeed plays a major role in our life. Because each and every situation that we face in our life we need to play our role with cent percent involvement and responsible for the consequences for that situation. 

This time I will try to explain the prime importance of this fourteen letter word with the help of a story. Hope you will like it.

Narration type-\> First person.

I feel the beads of on my forehead although the temperature in the room is 18^o^C. I’m neither preparing for exams nor I was caught doing something bizarre ;). It’s about a delivery that needs to be delivered to the customer that has already been delayed by 120 minutes. Time is now 9:00 A.M and I’m completely famished.

I heard a sweet lovely voice, when I was in this horrendous task, and it says “Hi, can you help me with this?”

I know she is cute and sweet and had it been on a normal day I would have explained the complete history of the work that she was asking but now it’s the wrong time and in haste I replied in my usual manner “ Sorry !!!, ask someone else or come later. I’m not free now.”

Everyone around me felt that I was rude but I hope that situation understanding will condone my behaviour.

Delivery went on smoothly and finally our customer got satisfied when his customer got satisfied but on the other side she is unhappy. I took that as a trade off as I felt that one should be more responsible to their work rather than relationship with co-worker.

Now it is 4:00 P.M in the evening, I stuck to my four wheeled chair for quarter a day and my spine is aching and sending signals to my grey matter to shut down the computer and get up. Finally I decided to delegate my work to my legs and slowly I took them towards the window glass and pulled down the curtain. Evening sun rays pierced the windows and landed on my eyes and boosted my mitochondria, all of a sudden I felt I saw a new world. Then slowly I asked Sun god to forgive me for showing off my back to him. Now I have seen two eye balls with more fierce and warm than that of the sun. I felt that I should go to her desk and ask whether she need any help but on the contrary I decided to evade as she is in need of help *she should approach me.*

Slowly the day faded away.

Next morning I kept on my soul in my banal work and completely involved to give an error free delivery. Suddenly those fierce eye balls flashed to my memory and I came to normal world and shook my head with smile and got up from my seat to see what she is doing now. But she isn’t there at her place and it happened for next one week. Through group manager I came to know that she is suffering from typhoid and will be coming to office in coming week.

From that instant; my mind created interest on her which finally led me to search for her on Facebook and sent a request to be a friend with her. Within few hours she responded the request and we started chatting together and it ended on that with exchange of our numbers. On that day I felt like flying up in the air as I was feeling more confidence, that I can accomplish anything in this world.

In next few days we got closer; most interesting is that we never spoke face to face but only through sms. Ice broke between us when on one day she called me late night and lately after an hour of chat, “I proposed her”. In response to my request for proposal she cut down the call and texted me for the reason for my act. I know there is no one on this earth who can give a perfect reason, at that time I thought I was too intelligent than her and I tried to justify my proposal through various ways; As usual she wasn’t pleased with anything.

Next day when I woke up early morning I realised the mistake I have done last night. But as I had proposed her I felt that it was my responsibility to commit myself to my act and for my words. Everyone knows that no one proposes to a girl in two weeks of their acquaintance unless it’s love at first sight. I thought that I should either say her that it was cent percent infatuation and went to office in the same notion when I was about to swipe my card into my zone; I received a text saying. “I think you are serious. I know you love me; but how can I perceive it unless you show it to me?”

I was dumb struck to respond to that text. As came to office with a different notion and that sms was a bolt out of blue. So, finally I said to myself that she will be my wife as I felt it is the only way to be more responsible for what I have done. I replied to that text saying that you will feel it in near future. But I know that my decision is abrupt and I don’t have any logical conclusion as how I could have decide about my better half without even completely getting to know about her; A lot of questions popped up in my mind however I struck to my decision that she is my wife for this life.\
\
Also, I felt that I love her truly with my cent percent emotions. Then I started to show her these emotions to her and she got confirmed that I was very true to her and accepted my proposal and in few months we got married.

After reading the story you may come to a conclusion that this story doesn’t go along with the title.\
\
But however if you observe the act he has been doing be it be in his work life or in his personal life he felt that his actions and the consequences of his action for which he is responsible is his responsibility. So, he held to himself that he is responsible albeit no one questioned to him. This is so because he constantly questioning to himself and tried to be as true as possible to himself. Similarly… { How can we decide about our better half in match-looking after speaking to them in quick time. But marriages, culture and authenticity sustained }

As we have age old adage “Necessity is the mother of invention”. Finally, I would like to complete the article by saying that “Responsibility is the father of fraternity”.