---
title: "Tenet, Axiom & Reality"
author: "Arun Koundinya Parasa"
date: "2020-12-19"
categories: [reflection]
image : "image.jpeg"
---

 [***Note***]{.underline}: This is not related to Value & Belief System

Few popular beliefs that we have in India are - " South Indians can't articulate much ", " By the age of 28 we have to get settled in life ", " The way they dress-up dictates their inner confidence " , " If a women boozes it is not right ", " Seeing is Believing " and etc.;

Beliefs are Tenets that help us to navigate the complex world for our comfort. As Brain is an energy expense organ it looks for short cuts to arrive at these beliefs based on our experience, information we processed and what we see.

If a person is having a belief that his belief system. If two people has the same belief it becomes a shared belief. If say entire community has that belief that it becomes a larger unquestionable belief. If say the entire community has that belief for a generation or a decade then most probably it becomes an axiom. 

The formation of these axioms has the same principles across organizations, homes and society. Most interesting aspect is that the formation of shared beliefs are stronger at younger age. The belief of person is authority has a larger influence on the downward hierarchy for the formation of belief system (*For example, children are strongly predisposed to believe their parents, and, as adults, we are inclined to believe authorities. Try experimenting to stepping down from authority - you will see that at times the same beliefs would not become shared and penetrated.* )

**Now when there is an axiom; why to worry about the truth???**

The Triumph of Truth gives a lasting pleasure than to be in the existing beliefs; Which of course helps us to learn from our mistakes and ignorances;

One such life story which i still remember to date is about the life story of Galileo Galilei who has faced all the odds and at the cost of personal ruin to tell about the truth to the world.

[***To Conclude***]{.underline}, 

-   Most Important hurdle in human life is to challenge their own inner core belief system. Once, we get convinced rest should be a piece of cake.

"Hesitating to act because the whole vision might not be achieved, or because others do not yet share it, is an attitude that only hinders progress." - M K Gandhi Ji.