---
title: "Consumer behaviour perspective from 30K feet above Sea Level"
author: "Arun Koundinya Parasa"
date: "2020-02-07"
categories: [consumerbehavior, psychology]
---

“Thy King, Thy People” was an age-old adage that we have been listening since childhoods for generations after generations. Does it still hold true in ‘Democracy’? since we (people) elect our own ruler. As I look at it, maybe the old-adage is applicable for families and organizations but when we relate to elections, it might not. Ruler in democratic state represents the majority of the collective mind-set of the people in that country or state at that time.

What is this to do with Consumer Behaviour? To my sense, it gives a different lens, as both the consumer and the voter are the same. It is just that our emotional preference changes from situation to situation.

For every elections all the parties comes up with their own value proposition (*usually termed in politics as manifesto or agenda*). At a thirty thousand feet level, each one of them has their own unique selling proposition to its target market. In politics, the hold on niche market does not help to be the leader of the house (*unless there is a hung*) but it is of several niche markets that is aggregate to its target market.

So, there are some more additional offers that parties usually provide in additional to their manifesto:

-   Segmented Offers like { Loan waiver for farmers who were hit with floods, Increased Pension etc.; }

-   Also, the previous term development {in both positive and negative way for either of the parties}.

Does all these logical benefits play a prominent role when it comes to D-Day of voting to that particular party?

The answer should be a straight “NO” as 

-   How many of us have read manifesto and communicated it to others

-   How many of us are part of those segmented offers

-   How many of us really keep a track of government development plans { When we have no time to carve of our development plan }

Therefore I feel, way-back politicians should have discovered the methodology of “Emotional Selling Proposition” {*ESP instead of USP*}. Now, it is becoming structured with certain organizations behaving as consulting wing for few parties when drafting the manifesto.

ESP helps in establishing the identity with respect to the party by dwelling the customer value funnel of Affiliation, Validation & Identity. 

How does this happen in reality?

Usually the people either affiliated or not affiliated. The latter would be easy targetable if we address their pain area. Usually behaviour identification of brand shifting is very harder (*because we usually patronize to a regular store/shop without much thinking about it once we start identified with the brand or few of its products*)

So during the election campaigns, the parties try to highlight/glorify that pain areas and gives oath to the people that they will resolve that pain {*during this phase they try to anchor that segment to shift their political affiliation*}. Since, each market faces different pain area they change the construct of the campaign communication in each market area. In addition, they try to ensure that they have a different representative face who understands the ground pain of the people who can address it when they are in power. These days with aid of external consultancy; these parties are trying to understand the real ground pains and refine their product and communication offering.

 This all looks good at 30K level above sea level. In the next blog, we will try to observe from sea level where in we will try to take the cues of writing of Zeithmal and Ram as well.

To conclude, Daniel Kahneman in his book ‘[***Thinking fast and slow***]{.underline}’ has mentioned that when faced with a choice; we are more likely to act to avert a loss than to achieve to gain.

[*Note*]{.underline}:
*1) The views mentioned in this article are personal views of the author and not affiliated to any parties or organizations.* 
*2) The core product and service execution plays a prominent role in terms of long-term affiliation for the brand/product.*