---
title: "What is Happiness?? - Part 2"
author: "Arun Koundinya Parasa"
date: "2019-07-13"
categories: [story, reflection]
---

Long back I have read an [***Antharyami***]{.underline} article in "Eenadu" NewsPaper { Largest circulated newspaper in AndhraPradesh & Telangana 

Link: [https://www.eenadu.net/newsdetails/16/2019/02/10/30522/Karmayogam](https://www.eenadu.net/newsdetails/16/2019/02/10/30522/Karmayogam)

In this blog i'm here to present a view that has its root in the above mentioned article. Hope you will like it.

This is a conversation between a Psychotherapist and an young software programmer in their third sitting.

Psychotherapist - Anupuma
Programmer - Kid

*Kid*:  Good Evening Ma'am.

*Anupuma*: Good Evening. You look better now. It is been almost couple of months since we meet. How have you been doing.

*Kid*: I'm doing good. Also, I'm getting better with myself.

*Anupuma*: Good to hear this from you.
*Kid*: Can I ask you one thing frankly.
*Anupuma*: Yes... Continue Please.
*Kid*: Although we spend so much effort in the right direction. Why there is failure?
*Anupuma*: Why there has to be a success??

Kid gave a confused look and asked again - "Success is prime, that keeps motivated to go ahead. Isn't it right?"

"Well, Well, Well; Of course that does. However when i asked why there has to be success", She paused and took a sip of water and continued,"I'm mentioning about the outcome."
"Dear, Success or Failure is a binary output variable for the work we do. Do you expect that you should have only 'success' in your life and not the failure?"

"I don't mean it Ma'am. I was saying that when we give our 100 percent effort to our fullest abilities and we know that we reached the goal. We expect a success and not a failure?"

"That is good."

"You mean failure is good".

She smiled and came beside him and said, " I mean about effort and the fact that you know that you reached your goal. It is a success for you."

"If there isn't anyone who would recognise it and take it forward. It is a pain. And what would I do with that success"\

"Let me clarify it my dear. There is a great difference between effort, performance, accomplishment and assessment", she got up and took the black marker and drawn a movie film projector and the screen.

She continued, " You remember the old movies. How they used to play. Unlike the digital projection now a days. A film is rolled and gets projected on the silver screen by aid of the projector.

Our brain projects what is in our schema.

In your scenario. your film projected that - since you did great effort and provided exemplary performance and you did accomplish that you feel. The assessment towards it should get added to make it a complete success.\

Isn't it so?"

Kid has gone into his deep thinking by trying to visualise and compare the set of events that has happened to him so far. And nodded the head.

Anupuma continued, " Also, you have tied your happiness with the complete success. Although you spent so much energy and effort you are unable to appreciate yourself."

"Can you explain me with a better example Ma'am. Am Unable to decipher what you are trying to say."

"Assume that you want to participate in 100m running race. So, get into participation you practice a lot, change your diet habits which is your effort. Say you want to finish the race in 15 seconds. You ran very well during the race and finished the race in say 14 seconds. This is called your performance and accomplishment.
Now say that you finished 3rd as the 1st and 2nd runner finished in 13.40 & 13.50 seconds respectively. Finally this is your assessment part where you have to assess on how to finish the next race on number 1 spot."
"If you tie up the happiness with the assessment part. It will lead to stress and disappointment."
"Also, event the top most cricket team as well loose matches; although they have best players in their team or how best they perform. However, the team assess on how to win the next match. The team morale will goes down if they go in virtuous cycle of stress and disappointment."

Anupuma paused for a minute and allowed the kid to digest the example and continued,
"Happiness is not a by product. It is a celebration of you being in the journey of your life"

"Thanks a lot Ma'am. I think i got a new contrary evidence to my schema which will help me to change my habits."\

"Come in fifteen days dear."

"Sure Ma'am. Thanks a lot".

I would like to end the article by saying that - LIVING is a present form speech. So, we have to be "In Present" while living.\

Note: It doesn't mean we should not have future plans. I recommend that we should not spoil our journey path for future.