---
title: "Humble & Assertiveness"
author: "Arun Koundinya Parasa"
date: "2018-10-07"
categories: [story, reflection]
---

I found myself on my reading desk with my left cheek on it. Slowly I made my spine straight and started massaging my forehead with my index finger such that my right eyebrow edge rests on my thumb. This is my usual style while I'm in deep thinking.

Now it is **6:20 A.M.**

I smiled and said to myself “Three nights on a row on reading table. Wow!!!”.

After my quick refreshment, had couple of brown bread slices along with a glass of low fat cow milk *(sugarless);* and then I'm back to my usual routine of reading morning newspaper.\

As i was about to start reading the newspaper. My eyes are closed with soft little fingers; I quickly realised it was of my beautiful kid.

"Very Good Morning my dear"

"Good Morning Papaaaa & Many Happy Returns of the day!!!" said my kid with so much excitement filled in eyes.

Life teaches us a lot. Specially, when our kids enter into our life it marks a special & tectonic shift in our priorities upon them. Be it how much they grow, they remain as our kids forever. One of the shifts is that we tend to forget our own birthdays.\
\
"Thank you a lot, my love."\
\
"Enjoy the day Papa. Will be back in couple of hours, got to attend a conference call."\
\
And I'm back to my usual routine for the day.\
\
Now it is 7**:20 A.M.**\
\
My wife isn't in town due to unavoidable circumstances; this resulted in completing three non-fiction books in three straight days. Today for a change i'm inclined to watch a movie series on NetFlix. No Sooner I got engrossed in Elementary Series for about 4 hours.\
\
Now it is 12 **NOON.**\
**\
**I'm completely famished; with the available bechamel sauce in the refrigerator and fusilli in the container;  i started preparing my favourite pasta which i learned from my Italian friend Andrea.  Lunch is prepared in no time.\
\
I'm yet to start as I'm expecting my child to be in dining room by this time. But it didn't happened. I'm perplexed as i never had such a lengthy conference call in my entire career,  and wondered how come this young kid got one. With this curious mindset i started climbing the stairs and knocked his home office room. { *This generation kids has no difference between home and office* }. My kid opened the door and sat on the table.\
\
At first i thought meeting is going on; but it took me little time to recognise that my kid is just staring at the computer. My old age concluded that the kid looks baffled.\
\
What happened dear!!! You look so confused!! Can I be of your help?"\
\
"Thanks a lot Papa. for so long in my life i have been bothering you for small and little things. I felt that, if I could not handle this situation you may feel low on me about my capability."\
\
"Remember Beta. Papa will never feel low about you. Papa only takes care about your long term happiness", I kissed on forehead and continued, "If I can be of your help. Can you explain me your situation".\
\
"Due to my poor communication and rapport with one of the most important client; my company was on the verge of loosing a quarter million dollar project. However, my boss saved me and the client has decided to go with our company with a string attached that I should not be the SPOC for the project. This morning my boss gave me a strong warning about my assertive behaviour and told to be humble toward my clients"\
\
Kid paused for a while and continued, "For last few years I'm only successful with my assertive behaviour which helped the company to get many valuable projects. How come my boss conclude about me with one such incident!"\
\
I smiled and said in a slow yet in strong voice, "Are you worried about your bosses comment or about your clients remark to your boss?"\
\
"Both"\
\
"If I tell you to choose only one and work on it; such that the other one will evade; which one do you prefer to choose?"\
\
"Of-course, i will worry about my clients comment as it might impact my future career. But he is one of the many clients that I handled."\
\
"You are on right track for half of it. But remember that he is the most important client".\
\
"Agree Papa. Do you expect me to be more humble? I have to be assertive to convince the customer about the product. Both humble and assertive cannot go hand-in-hand as i look at it."\
\
"Okie. Assume that you are right Beta. But on this special case it negates your fundamental thought process because of the incident that your experienced at your work place. Can you help me to download your definition of humble for me."\
\
"As per my understanding. It is lowering ones own self esteem; which of-course i cannot do it."\
\
"Are you sure about the definition."\
\
"Yes Papa. This is what the google says"\
\
"Let us assume that you are right. What happens to you if you behave humble".\
\
"Dad!!! I already told you"\
\
"Okie. Okie. I got it. Let me reframe such that i can get my answer. Does humble places you one step below your client and assertiveness on one step above?"\
\
"I never said it like that papa"\
\
"Don't lie to me beta. Just now you have said that humble means lowering your self esteem. Assume that if it is true. What happens to you if you behave in such a way."\
\
"Then....may be as i don't like to behave in such a way and I might force that particular behaviour on me. Which may lead to self punishing and impacting my confidence and self respect."\
\
"Great and Lovely answer my kid. To start with; let us take your last sentences that you mentioned - Humble is self punishing & leads to loose confidence and self respect"\
\
I paused for a second, to see how my kid is reacting on this. Kid seems to be curious about my further statements.\
\
So I continued, "Is it not near to Self Humiliation. As i look at it my dear, English is a very beautiful language. Every feeling has a different word and different context."\
\
And to further make my point i continued, "On the other side, you might be assuming that being assertive places a higher *importance-weightage* on your side. If you speak as if you are more important, people will assume that you are arrogant"\
\
Kid interrupted suddenly and said, "I would agree to your point on self humiliation but certainly not on Assertiveness & Arrogance. As assertive is being confident and arrogance is assuming that i know better than the other."\
\
"You are perfectly right my dear child. If you are assertive and not treating other person as equal as you. Then the other person assume that you are showing off your knowledge and superiority. And it is their right to assume."\
\
As my kid didn't interrupted i continued again, "Usually the side effects of self humiliation and arrogance is the same; we try to become more resistance from inside to protect our identity. During the phase of self-humiliation we tend to become resistant to uplift our image. While for the other we tend to become resistant to prove our point strongly. On the contrary, Humble & Assertiveness doesn't lead to a resistant behaviour."\
\
"Dad. This is beautiful to listen. Is it practically possible to be the both.???"\
\
I smiled and said,"All I'm saying is to treat the other person as equal as you, which is a better meaning for humble, and speak confidently about the point you want to convince. As i look it, convincing is about listening, understanding and sharing about a particular thing on which you are confident and interested."\
\
"Thanks a lot Dad. Few of them would have gone over my head. But I'm carrying a message that I have to humble & assertive towards my clients which solves both the party needs."\
\
"Lovely my child. I'm famished. Lets finish our lunch and rush for any movie. Let us enjoy the life buddy".