---
title: "Maturity & its Instant Immaturity"
author: "Arun Koundinya Parasa"
date: "2020-02-24"
categories: [reflection]
---

There are certain situations for many of us in our lives, where we say this banal dialogue to ourselves or to our closed ones. "I didn't expected him to behave like this.". (or)."He is very elderly person. What is the reason for his eccentric behaviour?" and like wise many questions.

There are a number of links on web starting from Wikipedia to many that explain about Psychological Maturity. This is just my view point on it.

My assertion is that humans doesn't have psychological maturity at all times. The underlying reason is that humans are emotional beings and are subject to varied emotions either by himself or due to external environment or Aura. { Aura is like the tag/brand that one carry }

There are two mistakes that usually we do. One is that we see the world from our view point and the second is that we expect the others to see the world from our view point. The problem doesn't lie in having a strong view point but the other way round. Also, depending upon our will power on that particular day or moment our comprehension capability varies to a large extent.

However, in any emotional turmoil or in a emotional hangover situation there is high chance that our intelligence is clouded by heavy emotions which makes us to react than to think. This moment is what i call as instant immaturity. Some realize this immaturity and correct their future behavior and some justify it adding it to their trait.

Let us take this concept little forward, Usually by nature we all have irresistible commotion to judge others and personify their character based on the situational patterns that we see or observe. Let us assume that theoretically we have read about "How a spouse should behave?". By all means spouse would not have behaved to that of our theoretical script that we read. Then we usually get into a conclusive state that spouse is not a spouse as its behavior is not depicting that of we read. So, here we can coin a new term called as 'insta judging.'\
\
In this example, we had shared a view point of author and got influenced by it to such an extent that we tried to juxtapose that particular view point on our spouse and didn't tried to understand our spouse. This is called as 'insta immuarity aided by judgement'\
\
By nature, in most of the cases, later we tend to adjust with our spouses and start living with them; luckily Bayes theorem comes in handy to rescue our relationship to change our view point. As we start seeing view point of our spouse and then slowly start buying it and eventually loving it in its due course.\
\
To Conclude, having a view point is our NATURE which drives our culture; Insta Judging is our HABIT that needs to be NURTURED to strengthen our culture.\
\
JAI HIND.