---
title: "Our Thinking - Our Life"
author: "Arun Koundinya Parasa"
date: "2018-10-27"
categories: [motivation, reflection]
---

By nature humans look to reduce the burden of their regular work. This is because we usually get bored by banal work. And this has propelled humans to think in a visionary way to place future generations in a comfort. On the other side, there are just around 1000 best inventions that has changed the world i.e.; from 'Controlled Fire' to latest 3D Printing.


[***Quick Summary of Uber View of Inventions***]{.underline}:

|                         |                           |                       |
|-------------|--------------|----------|
| **MileStone**           | **Time Period**           | **No. of Inventions** |
| The Ancient World       | 1,420,000 B.C. to 100 B.C | 200                   |
| From Rome to Revolution | 100 B.C. to 1800 A.D.     | 120                   |
| The Industrial Age      | 1800 A.D. to 1860 A.D     | 120                   |
| Rifle Ages              | 1860 A.D to 1890 A.D      | 110                   |
| Modern Age              | 1890 A.D to 1915 A.D      | 120                   |
| War & Peace             | 1915A.D to 1950 A.D       | 120                   |
| Going Global            | 1950 A.D. to 1969 A.D.    | 110                   |
| The Internet Age        | 1969 A.D to 2010 A.D      | 100                   |
|                         |                           | 1000                  |

Industrial Explosion has created a number of opportunities for inventions. Think about a person who was born in year 1950s and still alive; they might have experienced approximately 200 inventions during their life time. What they have seen is that world is expanding in quick time. In the above table if we had drawn another column say global population. The Invention Index Upon Population would be on a decreasing trend.

It is not that the people have become more lazy during the years. It is only that the inventions in the earlier ages were visible. So, identification of opportunity isn't a difficult but the methodology of invention was very difficult.

As we progressed, the implementation of invention and reachability of invention to larger people has became prominent as the opportunity identification of invention has become difficult than the methodology itself. {*Except a few*}

So on a survival note, that old person of 1950s communicate to their children as how privileged the current generation and how they should be smart in using the inventions for their better comfort and living in the society.

In reality, all of a sudden what we experience is to have more time at our perusal than our earlier generations. To quote a small example: paying an electricity bill in 1990 used to took at-least 20 minutes and in 2018 it takes hardly a minute through Paytm. So, what this generation experiences is that they have more time at their perusal than the earlier generation.

The main challenge is that what do we do with balance 19 Min.... i.e.; our brain would be idle for 19 min and we all know from the famous adage i.e.; [Idle man’s brain is devil's workshop]{.underline}. And now,  no one has guided us on how to use this balance time; so we leave it on auto-mode. { *In any generation, after our survival needs are met we had a leisure which was usually on an average used to spent with family, society, work, career etc.; { for some work is a survival need }.* }

In auto-mode as we are not steering ourselves; we usually react to the situations because survival instincts come into play. Which makes us to think in a negative way.

Say for example, we would like to kill the available time by taking to our love. However, love's mobile was on waiting. The immediate activity for most of the youth is to call their love until they pick the call and later to only hear the word "Lets break up". This usually happens because we get impatient and construct a negative imaginary world in quick time.

Our survival instincts are so powerful that it can think in multiple dimensions in quick time; but it is difficult to harness and maintain that power for a regular living. Leading only to damage our own inner peace. Quick solution that most of us get us is to divert our thinking on something else like reading, watching tv etc.; Which is like taking a pill and sleeping than arresting the root cause. 

As most of you might have read more 'self help' books than me; I would like to conclude the blog by saying that - If we want to steer our life into a happy zone we have to steer our thinking into a positive direction by taking the control of our thinking. The solution is not about managing the free time. It is about how are we living in free time in qualitative terms. Once we start living in those chunks of free time we start living in the moment and thus in our life. 

                                            Our Thinking - Our Life.